# Run poetry pre-commit hook to update requirements.txt
repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0  # add version here
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export

# Run ruff:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format # replaces Black

# Add pre-commit-hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

# Mypy does type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      types: [python]
      args: [--strict]
