# Run poetry pre-commit hook to update requirements.txt
repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0  # add version here
  hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export

# Run ruff:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.5
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format