task = 'los'
duration = 72

[data]
features = ['labevents', 'vitalsign']
batch_size = 50
num_workers = 4
bucket_size = 1
with_notes = false

[train]
epochs = 20
use_ratio = true
best_test_only = false
use_amp = true
learning_rate = 1e-1
