[tool.poetry]
name = "mm-healthfair"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"
matplotlib = "^3.8.3"
scikit-learn = "^1.4.1.post1"
torch = "^2.2.1"
seaborn = "^0.13.2"
ipykernel = "^6.29.3"
pre-commit = "^3.7.0"
dask = {extras = ["dataframe"], version = "^2024.4.0"}
tqdm = "^4.66.2"
toml = "^0.10.2"
types-toml = "^0.10.8.20240310"
ruff = "^0.3.5"

[tool.ruff]
select = [
    "F",  # Pyflakes
    "E",  # Pycodestyle
    "W",  # Pycodestyle
    "UP",  # pyupgrade
    "I",  # isort
    "PL", # Pylint
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
