[model]
fusion_method = 'concat'
st_first = true

[data]
batch_size = 64
num_workers = 15
modalities = ['timeseries', 'notes', 'static']

[train]
epochs = 100
learning_rate = 1e-2
early_stopping = 20

[paths]
model_paths = []
