[model]
fusion_method = 'concat'
st_first = true

[data]
batch_size = 16
num_workers = 0
modalities = ['timeseries', 'notes', 'static']

[train]
epochs = 100
learning_rate = 1e-2

[paths]
model_paths = []
